spring.application.name=vu

# Cấu hình kết nối SQL Server (Mặc định chạy ở port 1433)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=coursera_demo;encrypt=true;trustServerCertificate=true;

# Tài khoản đăng nhập SQL Server (Giấu bằng biến môi trường)
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Cấu hình JPA / Hibernate tự động tạo bảng cho SQL Server
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# CẤU HÌNH MAX SIZE UPLOAD FILE
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# CẤU HÌNH GOOGLE OAUTH2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

# CẤU HÌNH GỬI EMAIL (Giấu cả Email đăng nhập và Mật khẩu ứng dụng)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true